// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAhWlrZXDZWwdqXl9sX_1z63SDPQMlqhE',
    appId: '1:494969641765:web:35ad684e0417afc19d18cc',
    messagingSenderId: '494969641765',
    projectId: 'ecommerce-software2',
    authDomain: 'ecommerce-software2.firebaseapp.com',
    storageBucket: 'ecommerce-software2.firebasestorage.app',
    measurementId: 'G-56VKNHGG28',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQZO25TClHBmb19_LGZx7qwwyZjckOL40',
    appId: '1:494969641765:android:6a3124493a2aa6079d18cc',
    messagingSenderId: '494969641765',
    projectId: 'ecommerce-software2',
    storageBucket: 'ecommerce-software2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCvgqSQwZQADCU_vNtNyDQODpBQq26fbg',
    appId: '1:494969641765:ios:9442207a7cdf67909d18cc',
    messagingSenderId: '494969641765',
    projectId: 'ecommerce-software2',
    storageBucket: 'ecommerce-software2.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceSoftware2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCvgqSQwZQADCU_vNtNyDQODpBQq26fbg',
    appId: '1:494969641765:ios:9442207a7cdf67909d18cc',
    messagingSenderId: '494969641765',
    projectId: 'ecommerce-software2',
    storageBucket: 'ecommerce-software2.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceSoftware2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAhWlrZXDZWwdqXl9sX_1z63SDPQMlqhE',
    appId: '1:494969641765:web:91ed02119b805a3d9d18cc',
    messagingSenderId: '494969641765',
    projectId: 'ecommerce-software2',
    authDomain: 'ecommerce-software2.firebaseapp.com',
    storageBucket: 'ecommerce-software2.firebasestorage.app',
    measurementId: 'G-84XM4K1V2K',
  );
}
